<<<<<<< HEAD

set timing on;

-- 1.Write a SQL Query to find the number of female passengers who have made bookings for air  tickets?
SELECT COUNT(*) AS FEMALE_PASSENGERS FROM AIRLINE WHERE GENDER='Female';
-- Elapsed:  00:00:00:03



-- 2.Write a SQL Query to find the total number of passengers who have booked tickets in the business class?

SELECT COUNT(*) AS BUSINESS_CLASS FROM AIRLINE WHERE CLASS='Business';
-- Elapsed:  00:00:00:03



-- 3.Write a SQL Query to find the number of passengers who have booked tickets in the 'eco' class?

SELECT COUNT(*) AS ECO_CLASS FROM AIRLINE WHERE CLASS='Eco';
-- Elapsed:  00:00:00:03



-- 4.Write a SQL Query to find the number of children’s who are all book the tickets? (Childrens are below Age 13)

SELECT COUNT(*) AS CHILDRENS_BELOW_13 FROM AIRLINE WHERE AGE<13;
-- Elapsed:  00:00:00:03



-- 5.Write a SQL Query to count of passengers who are above the age of 16 and have booked tickets in the business class?

SELECT COUNT(*) AS BUSINESS_CLASS FROM AIRLINE WHERE AGE>16 AND CLASS='Business';
-- Elapsed:  00:00:00:04


-- SOLN 
CREATE BITMAP INDEX IDX2 ON AIRLINE(AGE,CLASS);
DROP INDEX IDX2;
-- Elapsed:  00:00:00:03

=======
-- Oracle Workspace Queries 

SET TIMING ON;

-- 1.WRITE A SQL QUERY TO FIND THE NUMBER OF FEMALE PASSENGERS WHO HAVE MADE BOOKINGS FOR AIR TICKETS?

SELECT COUNT(*) AS NO_OF_FEMALE_PASSENGERS FROM AIRLINE WHERE GENDER='Female';

-- 2.WRITE A SQL QUERY TO FIND THE TOTAL NUMBER OF PASSENGERS WHO HAVE BOOKED TICKETS IN THE BUSINESS CLASS?

SELECT COUNT(*) AS BOOKED_BUSINESS FROM AIRLINE WHERE CLASS='Business';

-- 3.WRITE A SQL QUERY TO FIND THE NUMBER OF PASSENGERS WHO HAVE BOOKED TICKETS IN THE ECO CLASS?

SELECT COUNT(*) AS BOOKED_ECO FROM AIRLINE WHERE CLASS='Eco';

-- 4. WRITE A SQL QUERY TO FIND THE NUMBER OF CHILDRENS WHO ARE ALL BOOK THE TICKETS? (CHILD AGE SHOULD BE BELOW 13)

SELECT COUNT(*) AS NO_OF_CHILDS FROM AIRLINE WHERE AGE<13;

-- 5. WRITE A SQL QUERY TO COUNT OF PASSENGERS WHO ARE ABOVE THE AGE OF 16 AND HAVE BOOKED TICKETS IN BUSINESS CLASS?

SELECT COUNT(*) AS ADULT_BUSINESS_CLASS FROM AIRLINE WHERE AGE>16 AND CLASS='Business';
>>>>>>> 90b6e90bd72072a5039eac614b21356dd56ba266
