-- Oracle Workspace Queries 

SET TIMING ON;

-- 1.WRITE A SQL QUERY TO FIND THE NUMBER OF FEMALE PASSENGERS WHO HAVE MADE BOOKINGS FOR AIR TICKETS?

SELECT COUNT(*) AS TOTAL_FEMALE_PASSENGERS FROM AIRLINE WHERE GENDER='Female';
-- Elapsed:  00:00:00:02



-- 2.WRITE A SQL QUERY TO FIND THE TOTAL NUMBER OF PASSENGERS WHO HAVE BOOKED TICKETS IN THE BUSINESS CLASS?

SELECT COUNT(*) AS BUSINESS_CLASS FROM AIRLINE WHERE CLASS='Business';
-- Elapsed:  00:00:00:03



-- 3.WRITE A SQL QUERY TO FIND THE NUMBER OF PASSENGERS WHO HAVE BOOKED TICKETS IN THE ECO CLASS?

SELECT COUNT(*) AS BOOKED_ECO FROM AIRLINE WHERE CLASS='Eco';
-- Elapsed:  00:00:00:03


-- 4. WRITE A SQL QUERY TO FIND THE NUMBER OF CHILDRENS WHO ARE ALL BOOK THE TICKETS? (CHILD AGE SHOULD BE BELOW 13)

SELECT COUNT(*) AS NO_OF_CHILDS FROM AIRLINE WHERE AGE<13;
-- Elapsed:  00:00:00:02



-- 5. WRITE A SQL QUERY TO COUNT OF PASSENGERS WHO ARE ABOVE THE AGE OF 16 AND HAVE BOOKED TICKETS IN BUSINESS CLASS?

SELECT COUNT(*) AS ADULT_BUSINESS_CLASS FROM AIRLINE WHERE AGE > 16 AND CLASS = 'Business';

--Elapsed:  00:00:00:03

-- SELECT ALL INDEXES FROM THE DATABASE
SELECT * FROM USER_INDEXES;

-- SOLN 
CREATE BITMAP INDEX AIRLINE_CLASS ON AIRLINE(AGE,CLASS);
