
set timing on;


CREATE OR REPLACE PROCEDURE C_TYPE
AS
    TYPE C_LIST IS TABLE OF number(10);
    CUS_LIST C_LIST := C_LIST();
    CUS_LIST2 C_LIST := C_LIST();
    S_TIME NUMBER;
    E_TIME NUMBER;
BEGIN
    s_TIME := DBMS_UTILITY.GET_TIME;
    SELECT S_ID 
    BULK COLLECT INTO CUS_LIST
    FROM AIRLINE WHERE AGE>16 AND CLASS='Business';
    E_TIME := DBMS_UTILITY.GET_TIME;
    DBMS_OUTPUT.PUT_LINE(E_TIME-S_TIME);
END;
/

BEGIN
    C_TYPE();
END;